//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SQL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class archivo
    {
        public archivo()
        {
            this.archivo_autor = new HashSet<archivo_autor>();
            this.comentario = new HashSet<comentario>();
            this.subir_descargar = new HashSet<subir_descargar>();
        }
    
        public int id_archivo { get; set; }
        public string nombre_archivo { get; set; }
        public string anio_archivo { get; set; }
        public string sinopsis_archivo { get; set; }
        public Nullable<int> num_pag { get; set; }
        public string imagen_portada { get; set; }
        public string url { get; set; }
        public string tags { get; set; }
        public int id_usuario { get; set; }
        public int id_estado { get; set; }
        public int id_categoria { get; set; }
        public int id_moderador { get; set; }
        public Nullable<int> estado_mod { get; set; }
        public Nullable<int> modified_by { get; set; }
    
        public virtual ICollection<archivo_autor> archivo_autor { get; set; }
        public virtual categoria categoria { get; set; }
        public virtual estado estado { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual ICollection<comentario> comentario { get; set; }
        public virtual ICollection<subir_descargar> subir_descargar { get; set; }
    }
}
