//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SQL_Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class Aula_Web_SQLEntities : DbContext
    {
        public Aula_Web_SQLEntities()
            : base("name=Aula_Web_SQLEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<archivo> archivo { get; set; }
        public DbSet<archivo_autor> archivo_autor { get; set; }
        public DbSet<autor> autor { get; set; }
        public DbSet<categoria> categoria { get; set; }
        public DbSet<comentario> comentario { get; set; }
        public DbSet<control_formulario> control_formulario { get; set; }
        public DbSet<control_idioma> control_idioma { get; set; }
        public DbSet<estado> estado { get; set; }
        public DbSet<formularios> formularios { get; set; }
        public DbSet<idiomas> idiomas { get; set; }
        public DbSet<pais> pais { get; set; }
        public DbSet<rol> rol { get; set; }
        public DbSet<subir_descargar> subir_descargar { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<tags> tags { get; set; }
        public DbSet<usuario> usuario { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_aprobar_archivo(Nullable<int> id_archivo, Nullable<int> id_categoria, Nullable<int> id, Nullable<int> dinero, Nullable<int> user_cambio)
        {
            var id_archivoParameter = id_archivo.HasValue ?
                new ObjectParameter("id_archivo", id_archivo) :
                new ObjectParameter("id_archivo", typeof(int));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dineroParameter = dinero.HasValue ?
                new ObjectParameter("dinero", dinero) :
                new ObjectParameter("dinero", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_aprobar_archivo", id_archivoParameter, id_categoriaParameter, idParameter, dineroParameter, user_cambioParameter);
        }
    
        public virtual int sp_cambiar_rol(Nullable<int> id, string nombre, string apellido, Nullable<long> documento, string telefono, string correo, string user, string clave, Nullable<int> dinero, Nullable<int> id_rol, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var documentoParameter = documento.HasValue ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(long));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var dineroParameter = dinero.HasValue ?
                new ObjectParameter("dinero", dinero) :
                new ObjectParameter("dinero", typeof(int));
    
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cambiar_rol", idParameter, nombreParameter, apellidoParameter, documentoParameter, telefonoParameter, correoParameter, userParameter, claveParameter, dineroParameter, id_rolParameter, user_cambioParameter);
        }
    
        public virtual int sp_cerrar_session(Nullable<int> id, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cerrar_session", idParameter, user_cambioParameter);
        }
    
        public virtual ObjectResult<sp_consulta_archivo_datos_Result> sp_consulta_archivo_datos(Nullable<int> id_rol)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_archivo_datos_Result>("sp_consulta_archivo_datos", id_rolParameter);
        }
    
        public virtual ObjectResult<sp_consulta_archivo_nombre_Result> sp_consulta_archivo_nombre(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_archivo_nombre_Result>("sp_consulta_archivo_nombre", nombreParameter);
        }
    
        public virtual ObjectResult<sp_consulta_autor_Result> sp_consulta_autor(string nom_autor)
        {
            var nom_autorParameter = nom_autor != null ?
                new ObjectParameter("nom_autor", nom_autor) :
                new ObjectParameter("nom_autor", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_autor_Result>("sp_consulta_autor", nom_autorParameter);
        }
    
        public virtual ObjectResult<sp_consulta_categoria_Result> sp_consulta_categoria(string categoria)
        {
            var categoriaParameter = categoria != null ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_categoria_Result>("sp_consulta_categoria", categoriaParameter);
        }
    
        public virtual ObjectResult<sp_consulta_correo_Result> sp_consulta_correo(string correo)
        {
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_correo_Result>("sp_consulta_correo", correoParameter);
        }
    
        public virtual ObjectResult<sp_consulta_documento_Result> sp_consulta_documento(Nullable<long> documento)
        {
            var documentoParameter = documento.HasValue ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_documento_Result>("sp_consulta_documento", documentoParameter);
        }
    
        public virtual ObjectResult<sp_consulta_idioma_Result> sp_consulta_idioma(string nombre)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_idioma_Result>("sp_consulta_idioma", nombreParameter);
        }
    
        public virtual ObjectResult<sp_consulta_rol_Result> sp_consulta_rol(Nullable<int> rol)
        {
            var rolParameter = rol.HasValue ?
                new ObjectParameter("rol", rol) :
                new ObjectParameter("rol", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_rol_Result>("sp_consulta_rol", rolParameter);
        }
    
        public virtual ObjectResult<sp_consulta_tags_Result> sp_consulta_tags(string tag)
        {
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_tags_Result>("sp_consulta_tags", tagParameter);
        }
    
        public virtual ObjectResult<sp_consulta_terminacion_Result> sp_consulta_terminacion(string terminacion)
        {
            var terminacionParameter = terminacion != null ?
                new ObjectParameter("terminacion", terminacion) :
                new ObjectParameter("terminacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_terminacion_Result>("sp_consulta_terminacion", terminacionParameter);
        }
    
        public virtual ObjectResult<sp_consulta_usuario_Result> sp_consulta_usuario(string usuario)
        {
            var usuarioParameter = usuario != null ?
                new ObjectParameter("usuario", usuario) :
                new ObjectParameter("usuario", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consulta_usuario_Result>("sp_consulta_usuario", usuarioParameter);
        }
    
        public virtual ObjectResult<sp_consultar_archivos_Result> sp_consultar_archivos(string parametro)
        {
            var parametroParameter = parametro != null ?
                new ObjectParameter("parametro", parametro) :
                new ObjectParameter("parametro", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_archivos_Result>("sp_consultar_archivos", parametroParameter);
        }
    
        public virtual ObjectResult<sp_consultar_comentarios_Result> sp_consultar_comentarios(Nullable<int> id_archivo)
        {
            var id_archivoParameter = id_archivo.HasValue ?
                new ObjectParameter("id_archivo", id_archivo) :
                new ObjectParameter("id_archivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_comentarios_Result>("sp_consultar_comentarios", id_archivoParameter);
        }
    
        public virtual ObjectResult<sp_consultar_idioma_Result> sp_consultar_idioma(Nullable<long> idioma, Nullable<long> formulario)
        {
            var idiomaParameter = idioma.HasValue ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(long));
    
            var formularioParameter = formulario.HasValue ?
                new ObjectParameter("formulario", formulario) :
                new ObjectParameter("formulario", typeof(long));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_consultar_idioma_Result>("sp_consultar_idioma", idiomaParameter, formularioParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_descargar_archivo(Nullable<int> id, Nullable<int> dinero, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var dineroParameter = dinero.HasValue ?
                new ObjectParameter("dinero", dinero) :
                new ObjectParameter("dinero", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_descargar_archivo", idParameter, dineroParameter, user_cambioParameter);
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_eliminar_archivo(Nullable<int> id, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_archivo", idParameter, user_cambioParameter);
        }
    
        public virtual int sp_eliminar_categoria(Nullable<int> id, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_categoria", idParameter, user_cambioParameter);
        }
    
        public virtual int sp_eliminar_tags(Nullable<int> id, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_eliminar_tags", idParameter, user_cambioParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_insertar_archivo(Nullable<int> id_rol, string nombre, string fecha, string sinopsis, Nullable<int> num_pag, string foto, string link, string tags, Nullable<int> id_user, Nullable<int> id_categoria, Nullable<int> user_cambio)
        {
            var id_rolParameter = id_rol.HasValue ?
                new ObjectParameter("id_rol", id_rol) :
                new ObjectParameter("id_rol", typeof(int));
    
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var fechaParameter = fecha != null ?
                new ObjectParameter("fecha", fecha) :
                new ObjectParameter("fecha", typeof(string));
    
            var sinopsisParameter = sinopsis != null ?
                new ObjectParameter("sinopsis", sinopsis) :
                new ObjectParameter("sinopsis", typeof(string));
    
            var num_pagParameter = num_pag.HasValue ?
                new ObjectParameter("num_pag", num_pag) :
                new ObjectParameter("num_pag", typeof(int));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(string));
    
            var linkParameter = link != null ?
                new ObjectParameter("link", link) :
                new ObjectParameter("link", typeof(string));
    
            var tagsParameter = tags != null ?
                new ObjectParameter("tags", tags) :
                new ObjectParameter("tags", typeof(string));
    
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var id_categoriaParameter = id_categoria.HasValue ?
                new ObjectParameter("id_categoria", id_categoria) :
                new ObjectParameter("id_categoria", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_archivo", id_rolParameter, nombreParameter, fechaParameter, sinopsisParameter, num_pagParameter, fotoParameter, linkParameter, tagsParameter, id_userParameter, id_categoriaParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_archivo_autor(string nombre, Nullable<int> user_cambio)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_archivo_autor", nombreParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_autor(string nombre, string fecha_birth, string fecha_death, string foto, string descripcion, Nullable<int> nacionalidad, Nullable<int> user_cambio)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var fecha_birthParameter = fecha_birth != null ?
                new ObjectParameter("fecha_birth", fecha_birth) :
                new ObjectParameter("fecha_birth", typeof(string));
    
            var fecha_deathParameter = fecha_death != null ?
                new ObjectParameter("fecha_death", fecha_death) :
                new ObjectParameter("fecha_death", typeof(string));
    
            var fotoParameter = foto != null ?
                new ObjectParameter("foto", foto) :
                new ObjectParameter("foto", typeof(string));
    
            var descripcionParameter = descripcion != null ?
                new ObjectParameter("descripcion", descripcion) :
                new ObjectParameter("descripcion", typeof(string));
    
            var nacionalidadParameter = nacionalidad.HasValue ?
                new ObjectParameter("nacionalidad", nacionalidad) :
                new ObjectParameter("nacionalidad", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_autor", nombreParameter, fecha_birthParameter, fecha_deathParameter, fotoParameter, descripcionParameter, nacionalidadParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_categoria(string categoria, Nullable<int> precio, Nullable<int> user_cambio)
        {
            var categoriaParameter = categoria != null ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_categoria", categoriaParameter, precioParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_comentario(Nullable<int> id, Nullable<int> id_archivo, string comentario, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var id_archivoParameter = id_archivo.HasValue ?
                new ObjectParameter("id_archivo", id_archivo) :
                new ObjectParameter("id_archivo", typeof(int));
    
            var comentarioParameter = comentario != null ?
                new ObjectParameter("comentario", comentario) :
                new ObjectParameter("comentario", typeof(string));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_comentario", idParameter, id_archivoParameter, comentarioParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_idioma(string idioma, string terminacion)
        {
            var idiomaParameter = idioma != null ?
                new ObjectParameter("idioma", idioma) :
                new ObjectParameter("idioma", typeof(string));
    
            var terminacionParameter = terminacion != null ?
                new ObjectParameter("terminacion", terminacion) :
                new ObjectParameter("terminacion", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_idioma", idiomaParameter, terminacionParameter);
        }
    
        public virtual int sp_insertar_ip_mac(Nullable<int> id, string ip, string mac, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var ipParameter = ip != null ?
                new ObjectParameter("ip", ip) :
                new ObjectParameter("ip", typeof(string));
    
            var macParameter = mac != null ?
                new ObjectParameter("mac", mac) :
                new ObjectParameter("mac", typeof(string));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_ip_mac", idParameter, ipParameter, macParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_subir_descargar(Nullable<int> id_user, Nullable<int> id_archivo, string concepto, Nullable<int> precio, Nullable<int> user_cambio)
        {
            var id_userParameter = id_user.HasValue ?
                new ObjectParameter("id_user", id_user) :
                new ObjectParameter("id_user", typeof(int));
    
            var id_archivoParameter = id_archivo.HasValue ?
                new ObjectParameter("id_archivo", id_archivo) :
                new ObjectParameter("id_archivo", typeof(int));
    
            var conceptoParameter = concepto != null ?
                new ObjectParameter("concepto", concepto) :
                new ObjectParameter("concepto", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_subir_descargar", id_userParameter, id_archivoParameter, conceptoParameter, precioParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_tags(string tag, Nullable<int> user_cambio)
        {
            var tagParameter = tag != null ?
                new ObjectParameter("tag", tag) :
                new ObjectParameter("tag", typeof(string));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_tags", tagParameter, user_cambioParameter);
        }
    
        public virtual int sp_insertar_usuario(string nombre, string apellido, Nullable<long> documento, string telefono, string correo, string user, string clave, Nullable<int> user_cambio)
        {
            var nombreParameter = nombre != null ?
                new ObjectParameter("nombre", nombre) :
                new ObjectParameter("nombre", typeof(string));
    
            var apellidoParameter = apellido != null ?
                new ObjectParameter("apellido", apellido) :
                new ObjectParameter("apellido", typeof(string));
    
            var documentoParameter = documento.HasValue ?
                new ObjectParameter("documento", documento) :
                new ObjectParameter("documento", typeof(long));
    
            var telefonoParameter = telefono != null ?
                new ObjectParameter("telefono", telefono) :
                new ObjectParameter("telefono", typeof(string));
    
            var correoParameter = correo != null ?
                new ObjectParameter("correo", correo) :
                new ObjectParameter("correo", typeof(string));
    
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var claveParameter = clave != null ?
                new ObjectParameter("clave", clave) :
                new ObjectParameter("clave", typeof(string));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insertar_usuario", nombreParameter, apellidoParameter, documentoParameter, telefonoParameter, correoParameter, userParameter, claveParameter, user_cambioParameter);
        }
    
        public virtual ObjectResult<sp_loggin_usuario_Result> sp_loggin_usuario(string user, string password)
        {
            var userParameter = user != null ?
                new ObjectParameter("user", user) :
                new ObjectParameter("user", typeof(string));
    
            var passwordParameter = password != null ?
                new ObjectParameter("password", password) :
                new ObjectParameter("password", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_loggin_usuario_Result>("sp_loggin_usuario", userParameter, passwordParameter);
        }
    
        public virtual int sp_modificar_categoria(Nullable<int> id, string categoria, Nullable<int> precio, Nullable<int> user_cambio)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            var categoriaParameter = categoria != null ?
                new ObjectParameter("categoria", categoria) :
                new ObjectParameter("categoria", typeof(string));
    
            var precioParameter = precio.HasValue ?
                new ObjectParameter("precio", precio) :
                new ObjectParameter("precio", typeof(int));
    
            var user_cambioParameter = user_cambio.HasValue ?
                new ObjectParameter("user_cambio", user_cambio) :
                new ObjectParameter("user_cambio", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_modificar_categoria", idParameter, categoriaParameter, precioParameter, user_cambioParameter);
        }
    
        public virtual ObjectResult<sp_mostrar_archivo_Result> sp_mostrar_archivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_archivo_Result>("sp_mostrar_archivo");
        }
    
        public virtual ObjectResult<sp_mostrar_archivos_Result> sp_mostrar_archivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_archivos_Result>("sp_mostrar_archivos");
        }
    
        public virtual ObjectResult<sp_mostrar_autor_Result> sp_mostrar_autor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_autor_Result>("sp_mostrar_autor");
        }
    
        public virtual ObjectResult<sp_mostrar_categoria_Result> sp_mostrar_categoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_categoria_Result>("sp_mostrar_categoria");
        }
    
        public virtual ObjectResult<sp_mostrar_categoria_archivo_Result> sp_mostrar_categoria_archivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_categoria_archivo_Result>("sp_mostrar_categoria_archivo");
        }
    
        public virtual ObjectResult<sp_mostrar_idioma_Result> sp_mostrar_idioma()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_idioma_Result>("sp_mostrar_idioma");
        }
    
        public virtual ObjectResult<sp_mostrar_pais_Result> sp_mostrar_pais()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_pais_Result>("sp_mostrar_pais");
        }
    
        public virtual ObjectResult<sp_mostrar_tags_Result> sp_mostrar_tags()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_mostrar_tags_Result>("sp_mostrar_tags");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual ObjectResult<sp_reporte_archivos_Result> sp_reporte_archivos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_archivos_Result>("sp_reporte_archivos");
        }
    
        public virtual ObjectResult<sp_reporte_autores_Result> sp_reporte_autores()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_autores_Result>("sp_reporte_autores");
        }
    
        public virtual ObjectResult<sp_reporte_usuarios_Result> sp_reporte_usuarios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_reporte_usuarios_Result>("sp_reporte_usuarios");
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    
        public virtual ObjectResult<sp_ver_archivo_Result> sp_ver_archivo(Nullable<int> id_archivo)
        {
            var id_archivoParameter = id_archivo.HasValue ?
                new ObjectParameter("id_archivo", id_archivo) :
                new ObjectParameter("id_archivo", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_archivo_Result>("sp_ver_archivo", id_archivoParameter);
        }
    
        public virtual ObjectResult<sp_ver_archivo_autor_Result> sp_ver_archivo_autor(Nullable<int> id_autor)
        {
            var id_autorParameter = id_autor.HasValue ?
                new ObjectParameter("id_autor", id_autor) :
                new ObjectParameter("id_autor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_archivo_autor_Result>("sp_ver_archivo_autor", id_autorParameter);
        }
    
        public virtual ObjectResult<sp_ver_autor_Result> sp_ver_autor(Nullable<int> id_autor)
        {
            var id_autorParameter = id_autor.HasValue ?
                new ObjectParameter("id_autor", id_autor) :
                new ObjectParameter("id_autor", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_ver_autor_Result>("sp_ver_autor", id_autorParameter);
        }
    }
}
