//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SQL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_idioma
    {
        public long id_control_idioma { get; set; }
        public long id_control { get; set; }
        public long id_idioma { get; set; }
        public string texto { get; set; }
    
        public virtual control_formulario control_formulario { get; set; }
        public virtual idiomas idiomas { get; set; }
    }
}
