//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SQL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class control_formulario
    {
        public control_formulario()
        {
            this.control_idioma = new HashSet<control_idioma>();
        }
    
        public long id_control_formulario { get; set; }
        public long id_formulario { get; set; }
        public string componente { get; set; }
    
        public virtual formularios formularios { get; set; }
        public virtual ICollection<control_idioma> control_idioma { get; set; }
    }
}
