//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data.SQL_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class estado
    {
        public estado()
        {
            this.archivo = new HashSet<archivo>();
        }
    
        public int id_estado { get; set; }
        public string estado1 { get; set; }
        public Nullable<int> modified_by { get; set; }
    
        public virtual ICollection<archivo> archivo { get; set; }
    }
}
